name: 🐞 Bug Report
description: For bugs that don't fit crash or ERM-specific categories
labels: "bug"
body:
- type: input
  attributes:
    label: ERA project version
    description: |
      What version of ERA project are you using?

      Note: Please only report issues for [latest versions of ERA project](https://github.com/ERA-Projects/era-project-eng/blob/main/CHANGELOG.md).
    placeholder: "2.0"
  validations:
    required: true

- type: dropdown
  attributes:
    label: If mods not included in the ERA project are used, does the error remain when they are disabled?
    options:
      - "Yes"
      - "No"
  validations:
    required: true

- type: checkbox
  attributes:
    label: Debug files and screenshots
    description: Please attach debug files, screenshots, or files using GitHub's file upload below.
    options:
      - "Ok"
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Describe what caused the error.
    description: Description of what happened
  validations:
    required: true
