name: Post Changelog to Discord

on:
  workflow_dispatch: # Allows manual execution

jobs:
  post_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read Version from ERA_Project.ini
        id: version
        run: |
          VERSION=$(grep 'Version=' ERA_Project.ini | cut -d'=' -f2 | tr -d '\r')
          echo "Detected version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Send Message to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "**The <@&800035036983984160> has been updated to version ${{ env.version }}**\nA big THANK YOU for your donations! They encourage me to work on the Assembly!"
          file: "CHANGELOG.md"
